build:
	CGO_ENABLED=0 GOOS=linux go build -o test1 cmd/*.go
	sudo chmod 777 test1
	cp test1 ~/Acexis/test/test1/at/
build-solution:
	CGO_ENABLED=0 GOOS=linux go build -o test1 cmd/*.go
	sudo chmod 777 test1
	cp test1 ~/Acexis/test/test1-solution/at/